"""Generate profile examples and field reference from bundled schema annotations."""

import argparse
import json
from pathlib import Path

from jsonschema import Draft202012Validator


PROJECT_DIR = Path(__file__).resolve().parents[1]
PROFILE_KINDS = ("native-character", "monster")


def describe(node, schema):
    """Summarize a field; the linked schema retains all validation constraints."""
    if "$ref" in node:
        node = schema["$defs"][node["$ref"].rsplit("/", 1)[1]]
    if "const" in node:
        return "constant `" + json.dumps(node["const"]) + "`"
    if "enum" in node:
        return ", ".join("`" + json.dumps(value) + "`" for value in node["enum"])
    if "anyOf" in node:
        return " or ".join(describe(branch, schema) for branch in node["anyOf"])
    kind = node.get("type", "see schema")
    result = " or ".join(kind) if isinstance(kind, list) else kind
    if kind == "array":
        result += " of " + describe(node["items"], schema)
    for key, label in (("minimum", "min"), ("maximum", "max"),
                       ("minItems", "min items"), ("minLength", "min length")):
        if key in node:
            result += f"; {label} {node[key]}"
    if node.get("uniqueItems"):
        result += "; unique"
    return result


def generated_files():
    outputs = {}
    lines = [
        "# Profile field reference", "",
        "Generated by `python scripts/generate_profile_docs.py`. Do not edit directly.",
        "Read [Profile formats](profile-formats.md) for loading, defaults, and examples.",
        "These tables summarize top-level fields; the linked schemas define nested",
        "objects, patterns, and cross-field constraints. Optional does not mean nullable.", "",
    ]
    for kind in PROFILE_KINDS:
        relative = f"src/dnd5ecombat/schemas/v1/{kind}.schema.json"
        schema = json.loads((PROJECT_DIR / relative).read_text(encoding="utf-8"))
        Draft202012Validator.check_schema(schema)
        example, = schema["examples"]
        Draft202012Validator(schema).validate(example)
        outputs[f"docs/examples/{kind}.json"] = json.dumps(example, indent=2) + "\n"
        lines += [f"## {schema['title']}", "",
                  f"[Schema](../{relative}) · [Complete example](examples/{kind}.json)", "",
                  "| Field | Required | Shape |", "| --- | --- | --- |"]
        for name, node in schema["properties"].items():
            required = "yes" if name in schema.get("required", ()) else "no"
            shape = describe(node, schema).replace("|", "\\|")
            lines.append(f"| `{name}` | {required} | {shape} |")
        lines.append("")
    outputs["docs/profile-reference.md"] = "\n".join(lines)
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    args = parser.parse_args()
    stale = []
    for relative, content in generated_files().items():
        path = PROJECT_DIR / relative
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        parser.exit(1, "Regenerate profile documentation: " + ", ".join(stale) + "\n")


if __name__ == "__main__":
    main()
